# Generated by Django 4.0 on 2022-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
